dataset: TUM
sequence: freiburg2_xyz
data_root: data/TUM

detector: superpoint
detector_params:
  weights_path: third_party/SuperGluePretrainedNetwork/models/weights/superpoint_v1.pth
  max_keypoints: 1024
  keypoint_threshold: 0.005
  nms_radius: 4
  use_cuda: true

matcher: superglue
matcher_params:
  weights_path: third_party/SuperGluePretrainedNetwork/models/weights/superglue_outdoor.pth
  sinkhorn_iterations: 20
  match_threshold: 0.2
  use_cuda: true

pose_estimation:
  method: essential
  ransac_thresh: 1.0
  ransac_conf: 0.999
  ransac_max_iters: 5000

evaluation:
  max_time_diff: 0.02
  rpe_delta: 1

output:
  trajectory_plot: traj_superpoint_superglue.png
  errors_plot: errors_superpoint_superglue.png
  plot_dpi: 150
